In [8]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

# Download latest version
path = kagglehub.dataset_download("walekhwatlphilip/intro-to-data-cleaning-eda-and-machine-learning")

print("Path to dataset files:", path)

/kaggle/input/private-dataset/bi.csv
/kaggle/input/private-dataset/intro-to-data-cleaning-eda-and-machine-learning.html
Path to dataset files: /kaggle/input/private-dataset

In [9]:
#Convertendo para UTF-8
caminho = "/kaggle/input/private-dataset/bi.csv"

df = pd.read_csv(caminho, encoding="latin1")

# Salva convertido
df.to_csv("/kaggle/working/bi.csv", index=False, encoding="utf-8")
df

,fNAME,lNAME,Age,gender,country,residence,entryEXAM,prevEducation,studyHOURS,Python,DB
0,Christina,Binger,44,Female,Norway,Private,72,Masters,158,59.0,55
1,Alex,Walekhwa,60,M,Kenya,Private,79,Diploma,150,60.0,75
2,Philip,Leo,25,Male,Uganda,Sognsvann,55,HighSchool,130,74.0,50
3,Shoni,Hlongwane,22,F,Rsa,Sognsvann,40,High School,120,NaN,44
4,Maria,Kedibone,23,Female,South Africa,Sognsvann,65,High School,122,91.0,80
...,...,...,...,...,...,...,...,...,...,...,...
72,Clara,Bernard,43,Female,France,Private,80,Bachelors,150,75.0,43
73,Julian,Nielsen,31,Male,Denmark,Sognsvann,90,Masters,158,84.0,83
74,Sophie,Brown,33,Female,UK,Sognsvann,96,Masters,158,85.0,90
75,Leon,Bauer,35,Male,Germany,Sognsvann,90,Masters,160,87.0,74
76,Mohammed,Salim,31,Male,Somali,Sognsvann,35,Masters,144,72.0,90

In [10]:
#Mostra estatísticas descritivas (média, desvio padrão, mínimo, máximo) 
#para identificar outliers (dados discrepantes).
df.describe()

             Age  entryEXAM  studyHOURS     Python          DB
count  77.000000  77.000000   77.000000  75.000000   77.000000
mean   35.207792  76.753247  149.714286  75.853333   69.467532
std    10.341966  16.475784   12.743272  15.410328   17.033701
min    21.000000  28.000000  114.000000  15.000000   30.000000
25%    27.000000  69.000000  144.000000  71.000000   56.000000
50%    33.000000  80.000000  156.000000  81.000000   71.000000
75%    42.000000  90.000000  158.000000  85.000000   83.000000
max    71.000000  98.000000  160.000000  91.000000  100.000000

In [11]:
#Exibe o tipo de cada coluna e a quantidade de valores nulos.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fNAME          77 non-null     object
 1   lNAME          77 non-null     object
 2   Age            77 non-null     int64
 3   gender         77 non-null     object
 4   country        77 non-null     object
 5   residence      77 non-null     object
 6   entryEXAM      77 non-null     int64
 7   prevEducation  77 non-null     object
 8   studyHOURS     77 non-null     int64
 9   Python         75 non-null     float64
 10  DB             77 non-null     int64
dtypes: float64(1), int64(4), object(6)
memory usage: 6.7+ KB

**Verificar Dados Nulos**

In [12]:
df.isnull().sum()

fNAME            0
lNAME            0
Age              0
gender           0
country          0
residence        0
entryEXAM        0
prevEducation    0
studyHOURS       0
Python           2
DB               0
dtype: int64

In [13]:
df['Python']

0     59.0
1     60.0
2     74.0
3      NaN
4     91.0
      ...
72    75.0
73    84.0
74    85.0
75    87.0
76    72.0
Name: Python, Length: 77, dtype: float64

In [14]:
df['Python'] = df['Python'].fillna("0")

In [15]:
df['Python']

0     59.0
1     60.0
2     74.0
3        0
4     91.0
      ...
72    75.0
73    84.0
74    85.0
75    87.0
76    72.0
Name: Python, Length: 77, dtype: object

**Verificar Duplicatas**

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.duplicated().any()

np.False_

In [18]:
df['fNAME'].value_counts()[df['fNAME'].value_counts() > 1]

fNAME
Grethe     2
Chinedu    2
Hanna      2
Odd        2
Bjørn      2
Emma       2
Name: count, dtype: int64

In [19]:
df[df['fNAME'] == 'Grethe']

,fNAME,lNAME,Age,gender,country,residence,entryEXAM,prevEducation,studyHOURS,Python,DB
13,Grethe,Myklebust,40,Female,Norway,Private,77,Diplomaaa,144,70.0,76
43,Grethe,Brekke,43,Female,Norway,Private,96,Masters,158,87.0,92

In [20]:
df[df['fNAME'].isin(['Grethe', 'Chinedu', 'Hanna', 'Bjørn', 'Odd', 'Emma'])] \
    .sort_values('fNAME')

,fNAME,lNAME,Age,gender,country,residence,entryEXAM,prevEducation,studyHOURS,Python,DB
8,Bjørn,Larsen,31,Male,Norway,BI Residence,88,Bachelors,156,80.0,89
52,Bjørn,Pedersen,21,Female,Norway,BI Residence,70,High School,138,69.0,47
53,Chinedu,Morison,36,Male,Nigeria,Private,28,Diploma,120,15.0,67
55,Chinedu,Okafor,69,Male,Nigeria,Private,94,Doctorate,160,87.0,88
10,Emma,de Vries,34,Female,Netherlands,BI Residence,65,Bachelors,156,79.0,58
70,Emma,Janssen,39,Female,Netherlands,Private,81,Masters,160,80.0,71
13,Grethe,Myklebust,40,Female,Norway,Private,77,Diplomaaa,144,70.0,76
43,Grethe,Brekke,43,Female,Norway,Private,96,Masters,158,87.0,92
16,Hanna,Andresen,45,Female,Norway,Private,85,Bachelors,156,87.0,82
21,Hanna,Isaksen,24,Female,Norway,BI Residence,50,High School,114,30.0,50
12,Odd,Knudsen,38,male,Norway,Private,91,DIPLOMA,156,85.0,99
24,Odd,Ahmed,30,Male,Norway,BI Residence,82,Bachelors,156,82.0,65

**Padronizar Dados**

In [21]:
df

,fNAME,lNAME,Age,gender,country,residence,entryEXAM,prevEducation,studyHOURS,Python,DB
0,Christina,Binger,44,Female,Norway,Private,72,Masters,158,59.0,55
1,Alex,Walekhwa,60,M,Kenya,Private,79,Diploma,150,60.0,75
2,Philip,Leo,25,Male,Uganda,Sognsvann,55,HighSchool,130,74.0,50
3,Shoni,Hlongwane,22,F,Rsa,Sognsvann,40,High School,120,0,44
4,Maria,Kedibone,23,Female,South Africa,Sognsvann,65,High School,122,91.0,80
...,...,...,...,...,...,...,...,...,...,...,...
72,Clara,Bernard,43,Female,France,Private,80,Bachelors,150,75.0,43
73,Julian,Nielsen,31,Male,Denmark,Sognsvann,90,Masters,158,84.0,83
74,Sophie,Brown,33,Female,UK,Sognsvann,96,Masters,158,85.0,90
75,Leon,Bauer,35,Male,Germany,Sognsvann,90,Masters,160,87.0,74
76,Mohammed,Salim,31,Male,Somali,Sognsvann,35,Masters,144,72.0,90

In [22]:
#Cabeçalho
df.columns = (
    df.columns
      .str.strip()          # remove espaços
      .str.lower()          # minúsculas
)

df.columns

Index(['fname', 'lname', 'age', 'gender', 'country', 'residence', 'entryexam',
       'preveducation', 'studyhours', 'python', 'db'],
      dtype='object')

In [23]:
#definir cabeçalhos
df.columns = [
    'first_name', 'last_name', 'age', 'gender',
    'country', 'residence', 'entry_exam',
    'previous_education', 'study_hours',
    'python', 'db_score'
]

df

,first_name,last_name,age,gender,country,residence,entry_exam,previous_education,study_hours,python,db_score
0,Christina,Binger,44,Female,Norway,Private,72,Masters,158,59.0,55
1,Alex,Walekhwa,60,M,Kenya,Private,79,Diploma,150,60.0,75
2,Philip,Leo,25,Male,Uganda,Sognsvann,55,HighSchool,130,74.0,50
3,Shoni,Hlongwane,22,F,Rsa,Sognsvann,40,High School,120,0,44
4,Maria,Kedibone,23,Female,South Africa,Sognsvann,65,High School,122,91.0,80
...,...,...,...,...,...,...,...,...,...,...,...
72,Clara,Bernard,43,Female,France,Private,80,Bachelors,150,75.0,43
73,Julian,Nielsen,31,Male,Denmark,Sognsvann,90,Masters,158,84.0,83
74,Sophie,Brown,33,Female,UK,Sognsvann,96,Masters,158,85.0,90
75,Leon,Bauer,35,Male,Germany,Sognsvann,90,Masters,160,87.0,74
76,Mohammed,Salim,31,Male,Somali,Sognsvann,35,Masters,144,72.0,90

In [24]:
# Trocar F por Female
df['gender'] = df['gender'].replace('F', 'Female')
df['gender'] = df['gender'].replace('M', 'Male')
df

#Observe que tem dados digitados errados

,first_name,last_name,age,gender,country,residence,entry_exam,previous_education,study_hours,python,db_score
0,Christina,Binger,44,Female,Norway,Private,72,Masters,158,59.0,55
1,Alex,Walekhwa,60,Male,Kenya,Private,79,Diploma,150,60.0,75
2,Philip,Leo,25,Male,Uganda,Sognsvann,55,HighSchool,130,74.0,50
3,Shoni,Hlongwane,22,Female,Rsa,Sognsvann,40,High School,120,0,44
4,Maria,Kedibone,23,Female,South Africa,Sognsvann,65,High School,122,91.0,80
...,...,...,...,...,...,...,...,...,...,...,...
72,Clara,Bernard,43,Female,France,Private,80,Bachelors,150,75.0,43
73,Julian,Nielsen,31,Male,Denmark,Sognsvann,90,Masters,158,84.0,83
74,Sophie,Brown,33,Female,UK,Sognsvann,96,Masters,158,85.0,90
75,Leon,Bauer,35,Male,Germany,Sognsvann,90,Masters,160,87.0,74
76,Mohammed,Salim,31,Male,Somali,Sognsvann,35,Masters,144,72.0,90

In [25]:
print(df['previous_education'].unique(), '\n')
print(df['residence'].unique(), '\n')
print(df['country'].unique(), '\n')

['Masters' 'Diploma' 'HighSchool' 'High School' 'Bachelors' 'Barrrchelors'
 'diploma' 'DIPLOMA' 'Diplomaaa' 'Doctorate']

['Private' 'Sognsvann' 'BI Residence' 'BI-Residence' 'BIResidence'
 'BI_Residence']

['Norway' 'Kenya' 'Uganda' 'Rsa' 'South Africa' 'Norge' 'norway' 'Denmark'
 'Netherlands' 'Italy' 'Spain' 'UK' 'Somali' 'Nigeria' 'Germany' 'France']

In [26]:
df['previous_education'] = df['previous_education'].replace('HighSchool', 'High School')
df['previous_education'] = df['previous_education'].replace('Diplomaaaa', 'Diploma')
df['previous_education'] = df['previous_education'].replace('Barrrchelors', 'Bachelors')

df['residence'] = df['residence'].replace('BI-Residence', 'BI Residence')
df['residence'] = df['residence'].replace('BI_Residence', 'BI Residence')
df['residence'] = df['residence'].replace('BIResidence', 'BI Residence')

#Primeira letra em Maiusculo
df['previous_education'] = df['previous_education'].str.title()
df['country'] = df['country'].str.title()

In [28]:
df
df.to_excel("/kaggle/working/bi-tratado.xlsx", index=False)